name: 'AWS Authentication'
description: 'Assumes IAM Role for GitHub Actions via OIDC'

inputs:
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: false
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: false
  aws-region:
    description: 'AWS Region'
    required: true
  role-to-assume:
    description: 'IAM Role ARN'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.role-to-assume }}
        role-session-name: GitHub_to_AWS_Deployment
        unset-current-credentials: true

    - name: Verify AWS identity
      run: aws sts get-caller-identity
      shell: bash
