AWSTemplateFormatVersion: '2010-09-09'
Description: Phoenix service stack (ECR, ALB, AutoScalingGroup with single t4g.small instance)

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
  InstanceType:
    Type: String
    Default: t4g.small
    AllowedValues: [t4g.small]
    Description: EC2 instance type (t4g.small for free-tier style usage)
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID where instances should be launched
  PublicSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of public subnet IDs (at least two) for the ALB and ASG
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-arm64-gp2
    Description: Latest Amazon Linux 2 ARM AMI ID

Resources:
  PhoenixEcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: phoenix-service

  PhoenixInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com]
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy

  PhoenixInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [ !Ref PhoenixInstanceRole ]

  PhoenixSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP, SSH, and docker-compose service ports
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        # SSH
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        # HTTP
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        # Phoenix Backend
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        # PostgreSQL
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0
        # Kafka & Kafka JMX
        - IpProtocol: tcp
          FromPort: 29092
          ToPort: 29092
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9404
          ToPort: 9404
          CidrIp: 0.0.0.0/0
        # Schema Registry
        - IpProtocol: tcp
          FromPort: 8081
          ToPort: 8081
          CidrIp: 0.0.0.0/0
        # Debezium
        - IpProtocol: tcp
          FromPort: 8083
          ToPort: 8083
          CidrIp: 0.0.0.0/0
        # Weaviate
        - IpProtocol: tcp
          FromPort: 8090
          ToPort: 8090
          CidrIp: 0.0.0.0/0
        # Ollama
        - IpProtocol: tcp
          FromPort: 11434
          ToPort: 11434
          CidrIp: 0.0.0.0/0
        # Prometheus
        - IpProtocol: tcp
          FromPort: 9090
          ToPort: 9090
          CidrIp: 0.0.0.0/0
        # Node Exporter
        - IpProtocol: tcp
          FromPort: 9100
          ToPort: 9100
          CidrIp: 0.0.0.0/0
        # Jaeger UI
        - IpProtocol: tcp
          FromPort: 16686
          ToPort: 16686
          CidrIp: 0.0.0.0/0
        # Grafana & LGTM
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3100
          ToPort: 3100
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3200
          ToPort: 3200
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 4318
          ToPort: 4319
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 4317
          ToPort: 4317
          CidrIp: 0.0.0.0/0
        # OpenTelemetry Collector
        - IpProtocol: tcp
          FromPort: 8889
          ToPort: 8889
          CidrIp: 0.0.0.0/0
        # Phoenix Frontend
        - IpProtocol: tcp
          FromPort: 5173
          ToPort: 5173
          CidrIp: 0.0.0.0/0

  PhoenixLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: phoenix-alb
      Scheme: internet-facing
      Type: application
      SecurityGroups: [ !Ref PhoenixSecurityGroup ]
      Subnets:
        - !Select [0, !Ref PublicSubnets]
        - !Select [1, !Ref PublicSubnets]

  PhoenixTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: phoenix-targets
      Port: 8080
      Protocol: HTTP
      TargetType: instance
      VpcId: !Ref VpcId

  PhoenixListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref PhoenixLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref PhoenixTargetGroup

  PhoenixLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: !Ref LatestAmiId
        InstanceType: !Ref InstanceType
        IamInstanceProfile:
          Name: !Ref PhoenixInstanceProfile
        SecurityGroupIds: [ !Ref PhoenixSecurityGroup ]
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash -xe
            set -e  # Exit immediately if a command fails
            exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1 # Log everything!
  
            echo "Starting Phoenix Bootstrap..."
            
            # 1. System Prep
            yum update -y || true
            yum install -y docker git jq || true
            
            # Create 5GB swap memory to prevent OOM
            # 2. Memory Management (Keep your 5GB Swap - it's a good move!)
            if [ ! -f /swapfile ]; then
            dd if=/dev/zero of=/swapfile bs=1G count=5
            chmod 600 /swapfile
            mkswap /swapfile
            swapon /swapfile
            echo '/swapfile none swap sw 0 0' >> /etc/fstab
            fi
            
            # Install docker-compose
            # 3. Docker Config
            curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose || true
            
            # Configure Docker daemon for better memory management
            mkdir -p /etc/docker
            cat > /etc/docker/daemon.json << 'EOF'
            {
              "storage-driver": "overlay2",
              "log-driver": "json-file",
              "log-opts": {
                "max-size": "10m",
                "max-file": "3"
              }
            }
            EOF
            
            systemctl enable --now docker || service docker start || true
            usermod -a -G docker ec2-user || true
            
            # 4. Use Native CFN Variables
            ACCOUNT_ID=${AWS::AccountId}
            REGION=${AWS::Region}
            ECR_REPO_URI="$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/phoenix-service"
            ECR_UI_URI="$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/phoenix-ui"
            
            # Login to ECR
            # 5. ECR Login
            aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com || true
            
            # Clone or Update repository
            cd /opt
            if [ ! -d "phoenix" ]; then
              git clone https://github.com/primusa/phoenix.git
            fi
            cd phoenix
            git pull || true
            
            # Pull ECR images for phoenix backend and frontend
            docker pull $ECR_REPO_URI:latest || true
            docker pull $ECR_UI_URI:latest || true
            
            # Create override file - Note the ! used to escape Bash variables from CloudFormation !Sub
            cat > docker-compose-override.yml << 'COMPOSE_EOF'
            services:
              phoenix-backend:
                image: ${!PHOENIX_ECR_URI}:latest
                restart: unless-stopped
                ports: [ "8080:8080" ]
                environment:
                  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
                  SPRING_KAFKA_PROPERTIES_ENABLE_METRICS_PUSH: "false"
                  SPRING_AI_VECTORSTORE_WEAVIATE_HOST: weaviate:8080
                  SPRING_AI_OLLAMA_BASE_URL: http://ollama:11434
                  SPRING_DATASOURCE_URL: jdbc:postgresql://legacy-db:5432/insurance_corp
                  SPRING_DATASOURCE_USERNAME: postgres
                  SPRING_DATASOURCE_PASSWORD: postgres
                  MANAGEMENT_OTLP_TRACING_ENDPOINT: http://otel-collector:4318/v1/traces
                  OTEL_DOTNET_AUTO_LOGS_INCLUDE_FORMATTED_MESSAGE: true
                  OTEL_INSTRUMENTATION_COMMON_DEFAULT_ENABLED: true
                  SPRING_AI_OLLAMA_CHAT_MODEL: tinyllama
                  MANAGEMENT_OPENTELEMETRY_TRACING_EXPORT_OTLP_ENDPOINT: http://otel-collector:4318/v1/traces
                  MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
                  MANAGEMENT_OTLP_METRICS_EXPORT_URL: http://otel-collector:4318/v1/metrics
                  MANAGEMENT_OTLP_METRICS_EXPORT_STEP: "10s"
                  MANAGEMENT_OPENTELEMETRY_LOGGING_EXPORT_OTLP_ENDPOINT: http://otel-collector:4318/v1/logs
                  MANAGEMENT_OPENTELEMETRY_LOGGING_EXPORT_ENABLED: "true"
                  MANAGEMENT_OPENTELEMETRY_INSTRUMENTATION_LOGBACK_APPENDER_ENABLED: "true"
                  LOGGING_STRUCTURED_FORMAT_CONSOLE: "otlp"
                depends_on: [ kafka, legacy-db, weaviate, jaeger, otel-collector ]
              
              phoenix-frontend:
                image: ${!PHOENIX_UI_ECR_URI}:latest
                restart: unless-stopped
                ports: [ "5173:8080" ]
                depends_on: [ phoenix-backend ]
            COMPOSE_EOF
            
            # Start docker-compose stack
            export PHOENIX_ECR_URI="$ECR_REPO_URI"
            export PHOENIX_UI_ECR_URI="$ECR_UI_URI"
            docker-compose -f docker-compose.yml -f docker-compose-override.yml up -d
            
            # Health Check Log
            sleep 10
            docker-compose ps

  PhoenixAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: !Ref PublicSubnets
      LaunchTemplate:
        LaunchTemplateId: !Ref PhoenixLaunchTemplate
        Version: !GetAtt PhoenixLaunchTemplate.LatestVersionNumber
      MinSize: '1'
      MaxSize: '1'
      DesiredCapacity: '1'
      TargetGroupARNs:
        - !Ref PhoenixTargetGroup

Outputs:
  EcrRepositoryUri:
    Value: !GetAtt PhoenixEcrRepository.RepositoryUri
    Export:
      Name: PhoenixEcrRepositoryUri
  LoadBalancerDns:
    Description: DNS name of the Application Load Balancer
    Value: !GetAtt PhoenixLoadBalancer.DNSName
    Export:
      Name: PhoenixLoadBalancerDns
