AWSTemplateFormatVersion: '2010-09-09'
Description: Phoenix service stack (dev :- single EC2, prod :- ALB + ASG + API Gateway)

Parameters:
  EnvironmentMode:
    Type: String
    AllowedValues: [development, production]
    Default: development

  VpcId:
    Type: AWS::EC2::VPC::Id

  InstanceType:
    Type: String
    Default: t4g.small

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Optional SSH access (SSM preferred)

  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-arm64-gp2

  PublicSubnetIds:
    Type: CommaDelimitedList
    Default: ""

  PrivateSubnetIds:
    Type: CommaDelimitedList
    Default: ""

  InternetGatewayId:
    Type: String
    Default: ""

  DeploymentId:
    Type: String
    Default: "initial"

  PublicSubnetCidr1: { Type: String, Default: 10.0.1.0/24 }
  PublicSubnetCidr2: { Type: String, Default: 10.0.2.0/24 }
  PrivateSubnetCidr1: { Type: String, Default: 10.0.10.0/24 }

  PhoenixServiceRepoName: { Type: String, Default: phoenix-service }
  PhoenixUiRepoName: { Type: String, Default: phoenix-ui }
  CreateALB: { Type: String, Default: "false" }

Conditions:
  IsProd: !Equals [!Ref EnvironmentMode, production]
  UseALB: !Or [!Condition IsProd, !Equals [!Ref CreateALB, "true"]]
  NotUseALB: !Not [!Condition UseALB]
  
  CreatePublicSubnets: !Equals [!Join ["", !Ref PublicSubnetIds], ""]
  CreatePrivateSubnets: !Equals [!Join ["", !Ref PrivateSubnetIds], ""]
  CreatePublicSubnet2: !And [!Condition CreatePublicSubnets, !Condition UseALB]
  
  CreateIGW: !Equals [!Ref InternetGatewayId, ""]

Resources:

  ########################
  # Networking
  ########################

  GeneratedIGW:
    Condition: CreateIGW
    DeletionPolicy: Retain
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags: [{ Key: Name, Value: phoenix-igw }]

  VPCGatewayAttachment:
    Condition: CreateIGW
    DeletionPolicy: Retain
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VpcId
      InternetGatewayId: !Ref GeneratedIGW

  PublicRouteTable:
    Condition: CreatePublicSubnets
    DeletionPolicy: Retain
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VpcId
      Tags: [{ Key: Name, Value: phoenix-public-rt }]

  PublicRoute:
    Condition: CreatePublicSubnets
    DeletionPolicy: Retain
    Type: AWS::EC2::Route
    # We depend on the attachment (if new) and the table itself
    DependsOn: [VPCGatewayAttachment, PublicRouteTable]
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !If [CreateIGW, !Ref GeneratedIGW, !Ref InternetGatewayId]

  PublicSubnet1:
    Condition: CreatePublicSubnets
    DeletionPolicy: Retain
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      CidrBlock: !Ref PublicSubnetCidr1
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags: [{ Key: Name, Value: phoenix-public-1 }]

  PublicSubnet1Association:
    Condition: CreatePublicSubnets
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2:
    Condition: CreatePublicSubnet2
    DeletionPolicy: Retain
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      CidrBlock: !Ref PublicSubnetCidr2
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [1, !GetAZs ""]
      Tags: [{ Key: Name, Value: phoenix-public-2 }]

  PublicSubnet2Association:
    Condition: CreatePublicSubnet2
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  PrivateSubnet1:
    Condition: CreatePrivateSubnets
    DeletionPolicy: Retain
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      CidrBlock: !Ref PrivateSubnetCidr1
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags: [{ Key: Name, Value: phoenix-private-1 }]

  ########################
  # IAM
  ########################

  PhoenixInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement: [{ Effect: Allow, Principal: { Service: ec2.amazonaws.com }, Action: sts:AssumeRole }]
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Tags: [{ Key: project, Value: phoenix }]

  PhoenixInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [!Ref PhoenixInstanceRole]

  ########################
  # Security Groups
  ########################

  ALBSecurityGroup:
    Condition: UseALB
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Public ALB access
      SecurityGroupIngress:
        - { IpProtocol: tcp, FromPort: 80, ToPort: 80, CidrIp: 0.0.0.0/0 }

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Phoenix instance group
      SecurityGroupIngress:
        # SSH always allowed (SSM preferred)
        - { IpProtocol: tcp, FromPort: 22, ToPort: 22, CidrIp: 0.0.0.0/0 }
        # Frontend, Backend, Grafana, Jaeger restricted to ALB if present
        - { IpProtocol: tcp, FromPort: 5173, ToPort: 5173, 
            CidrIp: !If [NotUseALB, 0.0.0.0/0, !Ref "AWS::NoValue"],
            SourceSecurityGroupId: !If [UseALB, !Ref ALBSecurityGroup, !Ref "AWS::NoValue"] }
        - { IpProtocol: tcp, FromPort: 8080, ToPort: 8080, 
            CidrIp: !If [NotUseALB, 0.0.0.0/0, !Ref "AWS::NoValue"],
            SourceSecurityGroupId: !If [UseALB, !Ref ALBSecurityGroup, !Ref "AWS::NoValue"] }
        - { IpProtocol: tcp, FromPort: 3000, ToPort: 3000, 
            CidrIp: !If [NotUseALB, 0.0.0.0/0, !Ref "AWS::NoValue"],
            SourceSecurityGroupId: !If [UseALB, !Ref ALBSecurityGroup, !Ref "AWS::NoValue"] }
        - { IpProtocol: tcp, FromPort: 16686, ToPort: 16686, 
            CidrIp: !If [NotUseALB, 0.0.0.0/0, !Ref "AWS::NoValue"],
            SourceSecurityGroupId: !If [UseALB, !Ref ALBSecurityGroup, !Ref "AWS::NoValue"] }
      SecurityGroupEgress:
        - { IpProtocol: -1, CidrIp: 0.0.0.0/0 }

  ########################
  # Launch Template
  ########################

  PhoenixLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: !Ref LatestAmiId
        InstanceType: !Ref InstanceType
        IamInstanceProfile: { Name: !Ref PhoenixInstanceProfile }
        KeyName: !Ref KeyName
        SecurityGroupIds: [ !Ref InstanceSecurityGroup ]
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              VolumeSize: 20
              VolumeType: gp3
              DeleteOnTermination: true
        MetadataOptions:
          HttpEndpoint: enabled
          HttpTokens: optional
          HttpPutResponseHopLimit: 2
        TagSpecifications:
          - ResourceType: instance
            Tags: [{ Key: project, Value: phoenix }, { Key: deployment-id, Value: !Ref DeploymentId }]
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash -xe
            set -e
            exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
            echo "Starting Phoenix Bootstrap (DeploymentId: ${DeploymentId})..."
            yum update -y
            yum install -y git jq
            amazon-linux-extras install docker -y
            systemctl enable --now docker
            for i in {1..10}; do [ -S /var/run/docker.sock ] && break || sleep 2; done
            
            if [ ! -f /swapfile ]; then
              dd if=/dev/zero of=/swapfile bs=1G count=5
              chmod 600 /swapfile
              mkswap /swapfile
              swapon /swapfile
              echo '/swapfile none swap sw 0 0' >> /etc/fstab
            fi
            
            curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose
            chmod +x /usr/bin/docker-compose
            usermod -a -G docker ec2-user
            
            ACCOUNT_ID=${AWS::AccountId}
            REGION=${AWS::Region}
            ECR_REPO_URI="$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/${PhoenixServiceRepoName}"
            ECR_UI_URI="$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/${PhoenixUiRepoName}"
            
            aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com || true
            
            cd /opt
            [ -d "phoenix" ] || git clone https://github.com/primusa/phoenix.git
            cd phoenix
            git pull
            docker system prune -af
            docker pull $ECR_REPO_URI:latest || true
            docker pull $ECR_UI_URI:latest || true
            
            export PHOENIX_ECR_URI="$ECR_REPO_URI"
            export PHOENIX_UI_ECR_URI="$ECR_UI_URI"
            
            cat > docker-compose-override.yml <<EOF
            services:
              phoenix-backend:
                image: ${!PHOENIX_ECR_URI}:latest
              phoenix-frontend:
                image: ${!PHOENIX_UI_ECR_URI}:latest
            EOF

            /usr/bin/docker-compose -f docker-compose.yml -f docker-compose-override.yml up -d
            chown -R ec2-user:ec2-user /opt/phoenix
            echo "Initializing Database..."
            bash ./init-db.sh || true
            echo "Setting up Debezium..."
            bash ./setup-debezium.sh || true
            sleep 10
            /usr/bin/docker-compose ps

  ########################
  # EC2 / ASG Resources
  ########################

  PhoenixInstance:
    Condition: NotUseALB
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref PhoenixLaunchTemplate
        Version: !GetAtt PhoenixLaunchTemplate.LatestVersionNumber
      SubnetId: !If [CreatePublicSubnets, !Ref PublicSubnet1, !Select [0, !Ref PublicSubnetIds]]
      Tags:
        - Key: project
          Value: phoenix
        - Key: Name
          Value: phoenix-instance
        - Key: DeletionOrderDependency
          Value: !If [CreatePublicSubnets, !Join ["-", [!Ref PublicSubnet1Association, !Ref PublicRoute]], "ExternalSubnet"]

  PhoenixLoadBalancer:
    Condition: UseALB
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Type: application
      Subnets: !If [CreatePublicSubnets, [!Ref PublicSubnet1, !Ref PublicSubnet2], !Ref PublicSubnetIds]
      SecurityGroups: [!Ref ALBSecurityGroup]

  FrontendTargetGroup:
    Condition: UseALB
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Port: 5173
      Protocol: HTTP

  BackendTargetGroup:
    Condition: UseALB
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Port: 8080
      Protocol: HTTP

  MonitoringTargetGroup:
    Condition: UseALB
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Port: 3000
      Protocol: HTTP

  JaegerTargetGroup:
    Condition: UseALB
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Port: 16686
      Protocol: HTTP

  PhoenixListener:
    Condition: UseALB
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref PhoenixLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions: [{ Type: forward, TargetGroupArn: !Ref FrontendTargetGroup }]

  AssetsRule:
    Condition: UseALB
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref PhoenixListener
      Priority: 5
      Actions: [{ Type: forward, TargetGroupArn: !Ref FrontendTargetGroup }]
      Conditions:
        - Field: path-pattern
          Values: [/assets/*]

  ApiRule:
    Condition: UseALB
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref PhoenixListener
      Priority: 10
      Actions: [{ Type: forward, TargetGroupArn: !Ref BackendTargetGroup }]
      Conditions:
        - Field: path-pattern
          Values: [/api/*]

  GrafanaRule:
    Condition: UseALB
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref PhoenixListener
      Priority: 20
      Actions: [{ Type: forward, TargetGroupArn: !Ref MonitoringTargetGroup }]
      Conditions:
        - Field: path-pattern
          Values: [/grafana*]

  JaegerRule:
    Condition: UseALB
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref PhoenixListener
      Priority: 30
      Actions: [{ Type: forward, TargetGroupArn: !Ref JaegerTargetGroup }]
      Conditions:
        - Field: path-pattern
          Values: [/jaeger*]

  PhoenixAutoScalingGroup:
    Condition: UseALB
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: !If [IsProd, !If [CreatePrivateSubnets, [!Ref PrivateSubnet1], !Ref PrivateSubnetIds], !If [CreatePublicSubnets, [!Ref PublicSubnet1], !Ref PublicSubnetIds]]
      LaunchTemplate:
        LaunchTemplateId: !Ref PhoenixLaunchTemplate
        Version: !GetAtt PhoenixLaunchTemplate.LatestVersionNumber
      MinSize: '1'
      MaxSize: '1'
      DesiredCapacity: '1'
      TargetGroupARNs: [!Ref FrontendTargetGroup, !Ref BackendTargetGroup, !Ref MonitoringTargetGroup, !Ref JaegerTargetGroup]
      Tags:
        - Key: project
          Value: phoenix
          PropagateAtLaunch: true
        - Key: DeletionOrderDependency
          Value: !If [CreatePublicSubnets, !Join ["-", [!Ref PublicSubnet1Association, !Ref PublicRoute]], "ExternalSubnet"]
          PropagateAtLaunch: true

  ########################
  # API Gateway
  ########################

  PhoenixApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub "${AWS::StackName}-api"
      ProtocolType: HTTP

  FrontendIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref PhoenixApi
      IntegrationType: HTTP_PROXY
      IntegrationUri: !If [UseALB, !Sub "http://${PhoenixLoadBalancer.DNSName}/", !Sub "http://${PhoenixInstance.PublicIp}:5173/"]
      PayloadFormatVersion: "1.0"
      IntegrationMethod: ANY

  AssetsIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref PhoenixApi
      IntegrationType: HTTP_PROXY
      IntegrationUri: !If [UseALB, !Sub "http://${PhoenixLoadBalancer.DNSName}/assets/", !Sub "http://${PhoenixInstance.PublicIp}:5173/assets/"]
      PayloadFormatVersion: "1.0"
      IntegrationMethod: ANY

  BackendIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref PhoenixApi
      IntegrationType: HTTP_PROXY
      IntegrationUri: !If [UseALB, !Sub "http://${PhoenixLoadBalancer.DNSName}/api/", !Sub "http://${PhoenixInstance.PublicIp}:8080/api/"]
      PayloadFormatVersion: "1.0"
      IntegrationMethod: ANY

  GrafanaIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref PhoenixApi
      IntegrationType: HTTP_PROXY
      IntegrationUri: !If [UseALB, !Sub "http://${PhoenixLoadBalancer.DNSName}/grafana/", !Sub "http://${PhoenixInstance.PublicIp}:3000/"]
      PayloadFormatVersion: "1.0"
      IntegrationMethod: ANY

  JaegerIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref PhoenixApi
      IntegrationType: HTTP_PROXY
      IntegrationUri: !If [UseALB, !Sub "http://${PhoenixLoadBalancer.DNSName}/jaeger/", !Sub "http://${PhoenixInstance.PublicIp}:16686/jaeger/"]
      PayloadFormatVersion: "1.0"
      IntegrationMethod: ANY

  DefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref PhoenixApi
      RouteKey: "$default"
      Target: !Join ["/", ["integrations", !Ref FrontendIntegration]]

  AssetsRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref PhoenixApi
      RouteKey: "ANY /assets/{proxy+}"
      Target: !Join ["/", ["integrations", !Ref AssetsIntegration]]

  BackendRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref PhoenixApi
      RouteKey: "ANY /api/{proxy+}"
      Target: !Join ["/", ["integrations", !Ref BackendIntegration]]

  GrafanaRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref PhoenixApi
      RouteKey: "ANY /grafana/{proxy+}"
      Target: !Join ["/", ["integrations", !Ref GrafanaIntegration]]

  JaegerRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref PhoenixApi
      RouteKey: "ANY /jaeger/{proxy+}"
      Target: !Join ["/", ["integrations", !Ref JaegerIntegration]]

  PhoenixApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref PhoenixApi
      StageName: "$default"
      AutoDeploy: true

Outputs:
  InstanceId: { Value: !If [NotUseALB, !Ref PhoenixInstance, "ASG managed"] }
  InstancePublicIp: { Condition: NotUseALB, Value: !GetAtt PhoenixInstance.PublicIp }
  LoadBalancerDns: { Condition: UseALB, Value: !GetAtt PhoenixLoadBalancer.DNSName }
  ApiGatewayUrl:
    Value: !Sub "https://${PhoenixApi}.execute-api.${AWS::Region}.amazonaws.com"
